/*
 * Petfinder API
 * The Petfinder API allows you to access the Petfinder database of hundreds of thousands of pets ready for adoption and over ten thousand animal welfare organizations.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@petfinder.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.petfinder.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AnimalsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-10T17:44:26.261741900+02:00[Asia/Jerusalem]")

public class AnimalsResponse {
    @SerializedName("animals")
    private List<Animal> animals = null;

    @SerializedName("pagination")
    private Pagination pagination = null;

    public AnimalsResponse animals(List<Animal> animals) {
        this.animals = animals;
        return this;
    }

    public AnimalsResponse addAnimalsItem(Animal animalsItem) {
        if (this.animals == null) {
            this.animals = new ArrayList<Animal>();
        }
        this.animals.add(animalsItem);
        return this;
    }

    /**
     * Get animals
     *
     * @return animals
     **/
    @Schema(description = "")
    public List<Animal> getAnimals() {
        return animals;
    }

    public void setAnimals(List<Animal> animals) {
        this.animals = animals;
    }

    public AnimalsResponse pagination(Pagination pagination) {
        this.pagination = pagination;
        return this;
    }

    /**
     * Get pagination
     *
     * @return pagination
     **/
    @Schema(description = "")
    public Pagination getPagination() {
        return pagination;
    }

    public void setPagination(Pagination pagination) {
        this.pagination = pagination;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AnimalsResponse AnimalsResponse = (AnimalsResponse) o;
        return Objects.equals(this.animals, AnimalsResponse.animals) &&
                Objects.equals(this.pagination, AnimalsResponse.pagination);
    }

    @Override
    public int hashCode() {
        return Objects.hash(animals, pagination);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AnimalsResponse {\n");

        sb.append("    animals: ").append(toIndentedString(animals)).append("\n");
        sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
