/*
 * Petfinder API
 * The Petfinder API allows you to access the Petfinder database of hundreds of thousands of pets ready for adoption and over ten thousand animal welfare organizations. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@petfinder.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.petfinder.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;

/**
 * AnimalTypeLinks
 */


@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-10T13:31:36.545254300+02:00[Asia/Jerusalem]")

public class AnimalTypeLinks {
  @SerializedName("self")
  private Link self = null;

  @SerializedName("breeds")
  private Link breeds = null;

  public AnimalTypeLinks self(Link self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @Schema(description = "")
  public Link getSelf() {
    return self;
  }

  public void setSelf(Link self) {
    this.self = self;
  }

  public AnimalTypeLinks breeds(Link breeds) {
    this.breeds = breeds;
    return this;
  }

   /**
   * Get breeds
   * @return breeds
  **/
  @Schema(description = "")
  public Link getBreeds() {
    return breeds;
  }

  public void setBreeds(Link breeds) {
    this.breeds = breeds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnimalTypeLinks animalTypeLinks = (AnimalTypeLinks) o;
    return Objects.equals(this.self, animalTypeLinks.self) &&
        Objects.equals(this.breeds, animalTypeLinks.breeds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, breeds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnimalTypeLinks {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    breeds: ").append(toIndentedString(breeds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
