/*
 * Petfinder API
 * The Petfinder API allows you to access the Petfinder database of hundreds of thousands of pets ready for adoption and over ten thousand animal welfare organizations. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@petfinder.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.petfinder.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrganizationSocialMedia
 */

import javax.annotation.processing.Generated;

@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-10T13:31:36.545254300+02:00[Asia/Jerusalem]")

public class OrganizationSocialMedia {
  @SerializedName("facebook")
  private String facebook = null;

  @SerializedName("instagram")
  private String instagram = null;

  @SerializedName("twitter")
  private String twitter = null;

  @SerializedName("pinterest")
  private String pinterest = null;

  @SerializedName("youtube")
  private String youtube = null;

  public OrganizationSocialMedia facebook(String facebook) {
    this.facebook = facebook;
    return this;
  }

   /**
   * Get facebook
   * @return facebook
  **/
  @Schema(description = "")
  public String getFacebook() {
    return facebook;
  }

  public void setFacebook(String facebook) {
    this.facebook = facebook;
  }

  public OrganizationSocialMedia instagram(String instagram) {
    this.instagram = instagram;
    return this;
  }

   /**
   * Get instagram
   * @return instagram
  **/
  @Schema(description = "")
  public String getInstagram() {
    return instagram;
  }

  public void setInstagram(String instagram) {
    this.instagram = instagram;
  }

  public OrganizationSocialMedia twitter(String twitter) {
    this.twitter = twitter;
    return this;
  }

   /**
   * Get twitter
   * @return twitter
  **/
  @Schema(description = "")
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  public OrganizationSocialMedia pinterest(String pinterest) {
    this.pinterest = pinterest;
    return this;
  }

   /**
   * Get pinterest
   * @return pinterest
  **/
  @Schema(description = "")
  public String getPinterest() {
    return pinterest;
  }

  public void setPinterest(String pinterest) {
    this.pinterest = pinterest;
  }

  public OrganizationSocialMedia youtube(String youtube) {
    this.youtube = youtube;
    return this;
  }

   /**
   * Get youtube
   * @return youtube
  **/
  @Schema(description = "")
  public String getYoutube() {
    return youtube;
  }

  public void setYoutube(String youtube) {
    this.youtube = youtube;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationSocialMedia organizationSocialMedia = (OrganizationSocialMedia) o;
    return Objects.equals(this.facebook, organizationSocialMedia.facebook) &&
        Objects.equals(this.instagram, organizationSocialMedia.instagram) &&
        Objects.equals(this.twitter, organizationSocialMedia.twitter) &&
        Objects.equals(this.pinterest, organizationSocialMedia.pinterest) &&
        Objects.equals(this.youtube, organizationSocialMedia.youtube);
  }

  @Override
  public int hashCode() {
    return Objects.hash(facebook, instagram, twitter, pinterest, youtube);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationSocialMedia {\n");
    
    sb.append("    facebook: ").append(toIndentedString(facebook)).append("\n");
    sb.append("    instagram: ").append(toIndentedString(instagram)).append("\n");
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    pinterest: ").append(toIndentedString(pinterest)).append("\n");
    sb.append("    youtube: ").append(toIndentedString(youtube)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
