/*
 * Petfinder API
 * The Petfinder API allows you to access the Petfinder database of hundreds of thousands of pets ready for adoption and over ten thousand animal welfare organizations. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@petfinder.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.petfinder.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.List;
/**
 * Organization
 */

@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-10T13:31:36.545254300+02:00[Asia/Jerusalem]")

public class Organization {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("address")
  private AnimalContactAddress address = null;

  @SerializedName("hours")
  private OrganizationHours hours = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("website")
  private String website = null;

  @SerializedName("mission_statement")
  private String missionStatement = null;

  @SerializedName("adoption")
  private OrganizationAdoption adoption = null;

  @SerializedName("social_media")
  private OrganizationSocialMedia socialMedia = null;

  @SerializedName("photos")
  private List<Photo> photos = null;

  @SerializedName("_links")
  private OrganizationLinks _links = null;

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "NJ333", description = "")
  public String getId() {
    return id;
  }

  public Organization name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "A+ Pet Shelter", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Organization email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Organization phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @Schema(description = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Organization address(AnimalContactAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public AnimalContactAddress getAddress() {
    return address;
  }

  public void setAddress(AnimalContactAddress address) {
    this.address = address;
  }

  public Organization hours(OrganizationHours hours) {
    this.hours = hours;
    return this;
  }

   /**
   * Get hours
   * @return hours
  **/
  @Schema(description = "")
  public OrganizationHours getHours() {
    return hours;
  }

  public void setHours(OrganizationHours hours) {
    this.hours = hours;
  }

  public Organization url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Organization website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @Schema(description = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public Organization missionStatement(String missionStatement) {
    this.missionStatement = missionStatement;
    return this;
  }

   /**
   * Get missionStatement
   * @return missionStatement
  **/
  @Schema(description = "")
  public String getMissionStatement() {
    return missionStatement;
  }

  public void setMissionStatement(String missionStatement) {
    this.missionStatement = missionStatement;
  }

  public Organization adoption(OrganizationAdoption adoption) {
    this.adoption = adoption;
    return this;
  }

   /**
   * Get adoption
   * @return adoption
  **/
  @Schema(description = "")
  public OrganizationAdoption getAdoption() {
    return adoption;
  }

  public void setAdoption(OrganizationAdoption adoption) {
    this.adoption = adoption;
  }

  public Organization socialMedia(OrganizationSocialMedia socialMedia) {
    this.socialMedia = socialMedia;
    return this;
  }

   /**
   * Get socialMedia
   * @return socialMedia
  **/
  @Schema(description = "")
  public OrganizationSocialMedia getSocialMedia() {
    return socialMedia;
  }

  public void setSocialMedia(OrganizationSocialMedia socialMedia) {
    this.socialMedia = socialMedia;
  }

  public Organization photos(List<Photo> photos) {
    this.photos = photos;
    return this;
  }

  public Organization addPhotosItem(Photo photosItem) {
    if (this.photos == null) {
      this.photos = new ArrayList<Photo>();
    }
    this.photos.add(photosItem);
    return this;
  }

   /**
   * Get photos
   * @return photos
  **/
  @Schema(description = "")
  public List<Photo> getPhotos() {
    return photos;
  }

  public void setPhotos(List<Photo> photos) {
    this.photos = photos;
  }

  public Organization _links(OrganizationLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public OrganizationLinks getLinks() {
    return _links;
  }

  public void setLinks(OrganizationLinks _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Organization organization = (Organization) o;
    return Objects.equals(this.id, organization.id) &&
        Objects.equals(this.name, organization.name) &&
        Objects.equals(this.email, organization.email) &&
        Objects.equals(this.phone, organization.phone) &&
        Objects.equals(this.address, organization.address) &&
        Objects.equals(this.hours, organization.hours) &&
        Objects.equals(this.url, organization.url) &&
        Objects.equals(this.website, organization.website) &&
        Objects.equals(this.missionStatement, organization.missionStatement) &&
        Objects.equals(this.adoption, organization.adoption) &&
        Objects.equals(this.socialMedia, organization.socialMedia) &&
        Objects.equals(this.photos, organization.photos) &&
        Objects.equals(this._links, organization._links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, email, phone, address, hours, url, website, missionStatement, adoption, socialMedia, photos, _links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organization {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    missionStatement: ").append(toIndentedString(missionStatement)).append("\n");
    sb.append("    adoption: ").append(toIndentedString(adoption)).append("\n");
    sb.append("    socialMedia: ").append(toIndentedString(socialMedia)).append("\n");
    sb.append("    photos: ").append(toIndentedString(photos)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
