/*
 * Petfinder API
 * The Petfinder API allows you to access the Petfinder database of hundreds of thousands of pets ready for adoption and over ten thousand animal welfare organizations. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help@petfinder.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.petfinder.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Photo
 */

import javax.annotation.processing.Generated;

@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-10T13:31:36.545254300+02:00[Asia/Jerusalem]")

public class Photo {
  @SerializedName("small")
  private String small = null;

  @SerializedName("medium")
  private String medium = null;

  @SerializedName("large")
  private String large = null;

  @SerializedName("full")
  private String full = null;

  public Photo small(String small) {
    this.small = small;
    return this;
  }

   /**
   * Get small
   * @return small
  **/
  @Schema(description = "")
  public String getSmall() {
    return small;
  }

  public void setSmall(String small) {
    this.small = small;
  }

  public Photo medium(String medium) {
    this.medium = medium;
    return this;
  }

   /**
   * Get medium
   * @return medium
  **/
  @Schema(description = "")
  public String getMedium() {
    return medium;
  }

  public void setMedium(String medium) {
    this.medium = medium;
  }

  public Photo large(String large) {
    this.large = large;
    return this;
  }

   /**
   * Get large
   * @return large
  **/
  @Schema(description = "")
  public String getLarge() {
    return large;
  }

  public void setLarge(String large) {
    this.large = large;
  }

  public Photo full(String full) {
    this.full = full;
    return this;
  }

   /**
   * Get full
   * @return full
  **/
  @Schema(description = "")
  public String getFull() {
    return full;
  }

  public void setFull(String full) {
    this.full = full;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Photo photo = (Photo) o;
    return Objects.equals(this.small, photo.small) &&
        Objects.equals(this.medium, photo.medium) &&
        Objects.equals(this.large, photo.large) &&
        Objects.equals(this.full, photo.full);
  }

  @Override
  public int hashCode() {
    return Objects.hash(small, medium, large, full);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Photo {\n");
    
    sb.append("    small: ").append(toIndentedString(small)).append("\n");
    sb.append("    medium: ").append(toIndentedString(medium)).append("\n");
    sb.append("    large: ").append(toIndentedString(large)).append("\n");
    sb.append("    full: ").append(toIndentedString(full)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
